import pandas as pd


configfile: "configs/config.yaml"

# Create all the metadata files and format them
df_cage = pd.read_csv('configs/cage_metadata.tsv',
                      sep='\t').set_index('File accession')
df_rampage = pd.read_csv('configs/rampage_metadata.tsv',
                         sep='\t').set_index('File accession')

df_mapping = pd.read_csv(
    'lr_bulk/biosamp_term_name_map.tsv', sep='\t', header=None)
df_mapping = df_mapping[[0, 4]] \
    .rename(columns={0: 'Experiment accession', 4: 'sample'}) \
    .set_index('Experiment accession')

df_lr = pd.read_csv('lr_bulk/metadata.tsv', sep='\t') \
    .set_index('Experiment accession') \
    .join(df_mapping) \
    .reset_index() \
    .set_index('File accession')

df_bru = pd.read_csv('configs/bru_metadata.tsv', sep='\t')
df_bru = df_bru[df_bru['Output type'].str.contains('unique')] \
    .set_index('File accession')

df_short = pd.read_csv('configs/short_metadata.tsv', sep='\t') \
             .set_index('File accession')

include: "download/Snakefile"
include: "common/Snakefile"
include: "lapa/Snakefile"
include: "igv/Snakefile"
include: "tss/Snakefile"
include: "miRNA/Snakefile"
include: "splicing/Snakefile"
include: "plot/Snakefile"


rule all:
    input:
        rules.all_download.input
        # rules.all_splicing.input
        # rules.all_lapa.input
        # rules.all_miRNA.input
