rule extract_three_prime_utr:
    input:
        gtf = config['talon']['gtf_corrected'],
        cds = config['gencode']['cds']
    threads: 1
    resources:
        mem_gb = 16
    output:
        bed = config['polya']['three_prime_utr']
    script:
        "./three_prime_utr.py"


rule louef_genes:
    input:
        lof = config['gnomad']['constraint'],
        gtf = config['gtf']
    threads: 1
    resources:
        mem_gb = 16
    output:
        csv = config['gnomad']['loeuf_decile']
    script:
        "./louef_decile_genes.py"


rule gnomad_variants_in_3utr:
    input:
        vcf = config['gnomad']['vcf'],
        bed = config['polya']['three_prime_utr']
    threads: 1
    resources:
        mem_gb = 16
    output:
        csv = config['polya']['variants_utr_chrom']
    script:
        "./variants_in_3utr.py"


rule gnomad_variants_in_polya:
    input:
        vcf = config['gnomad']['vcf'],
        lapa_dir = config['lapa']['tes'],
        bed = config['polya']['three_prime_utr']
    threads: 1
    resources:
        mem_gb = 16
    output:
        csv = config['polya']['variants_polya_chrom']
    script:
        "./variants_in_polya.py"


rule gnomad_loeuf_genes_polyA_signal:
    input:
        lapa_dir = config['lapa']['tes'],
        loeuf_decile = config['gnomad']['loeuf_decile'],
        variant_polya = expand(config['polya']['variants_polya_chrom'],
                               chrom=config['chroms']),
        variant_3utr = expand(config['polya']['variants_utr_chrom'],
                              chrom=config['chroms'])
    threads: 1
    resources:
        mem_gb = 16
    output:
        fig_loeuf = 'reports/figures/polyA/loeuf_polyA_signal.png',
        fig_signal = 'reports/figures/polyA/signal_usage.png'
    notebook:
        "./loeuf_genes_polya_signal.ipynb"


rule all_polyA:
    input:
        rules.gnomad_loeuf_genes.output
