name: rnawg
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python
  - samtools
  - igvtools
  - pip:
    - cython
    - snakemake
    - jupyter
    - sklearn
    - notebook
    - pytest
    - pyfaidx
    - seaborn
    - snakemk_util
    - gdown
    - igv-notebook
    - liftover
    - more-itertools
    - kipoiseq
    - git+https://github.com/mortazavilab/lapa.git#egg=lapa
    - git+https://github.com/MuhammedHasan/gencode_utr_fix.git#egg=gencode_utr_fix
