rule polya_signal_variants:
    input:
        vcf = config['gnomad']['vcf'],
        lapa_dir = directory(config['lapa']['tes'])
    threads: 1
    resources:
        mem_gb = 8
    output:
        config['polya']['variants_polya_chrom']
    script:
        "./polya_variants.py"


rule all_polya:
    input:
        expand(config['polya']['variants_polya_chrom'], chrom=config['chroms'])
