drive_id:
  human:
    read_annot: 1ZBMd4p73TlYsox5KNEkqJqm_u9xvQec7
    gtf: 1O_Vd5-SjyBE9MjxFsoLBjD43Tx7kw-T5
    abundance: 1repLKHfQYV66MEv0FweyKJxtvvs4sFlj

  # move to mouse repo
  # mouse:
  #   read_annot: 1xW2oLzmu2OE2fZwZAO6SUwMebLQP4Ve_
  #   gtf: 1iAT5iqcmqUyfjYGQwYyYk6j9KEJbLUz9
  #   abundance: 1nGb8NZ4m0a9CqA54bJb-rTrhUrTQeyeo

fasta: data/resources/common/{specie}.fasta
gtf_raw: data/resources/common/{specie}.gtf
gtf: data/resources/wg/common/{specie}.utr_fix.gtf
chrom_sizes: data/resources/common/{specie}.chrom_sizes

talon:
  gtf: data/resources/talon/{specie}_talon.gtf 
  abundance_unfiltered: data/resources/talon/{specie}_talon_abundance.tsv
  abundance: data/resources/talon/{specie}_talon_abundance_filtered.tsv
  read_annot: data/resources/talon/{specie}_talon_read_annot.tsv

  gtf_corrected: data/results/talon/{specie}_talon.corrected.gtf
  abundance_corrected: data/results/talon/{specie}_talon_abundance_filtered.corrected.tsv

cCREs:
  promotors: data/resources/cCREs/GRCh38-PLS.bed
  proximal_enhancers: data/resources/cCREs/GRCh38-ccREs.pELS.bed
  distal_enhancers: data/resources/cCREs/GRCh38-ccREs.dELS.bed

fantom: data/resources/fantom/hg38_CAGE.bed

cage:
  bed: data/resources/cage/idr_peak/{encode_id}.bed
  merged: data/resources/cage/merged.bed
  
rampage:
  bed: data/resources/rampage/idr_peak/{encode_id}.bed
  merged: data/resources/rampage/merged.bed

lapa:
  tes: data/results/lapa/wg_lapa_{specie}
  tss: data/results/lapa_tss/wg_lapa_{specie}
  link: data/results/wg_{specie}_lapa_tss_to_tes_links.csv

igv:
  gtf_sorted: data/results/igv/{specie}.utr_fix.sorted.gtf
  gtf_talon_sorted: data/results/igv/{specie}_talon.sorted.gtf
  gtf_talon_corrected_sorted: data/results/igv/{specie}_talon.corrected.sorted.gtf
